services:
  rodgermd.type.image_file:
    class: Rodgermd\SfToolsBundle\Type\ImageType
    tags:
        - { name: form.type, alias: image }

  rodgermd.type.image_delete_file:
    class: Rodgermd\SfToolsBundle\Type\ImageDeleteType
    tags:
        - { name: form.type, alias: image_delete }

  rodgermd.type.rich_text:
    class: Rodgermd\SfToolsBundle\Type\RichTextType
    tags:
      - { name: form.type, alias: rich_text }
  rodgermd.twig.images_extension:
    class: Rodgermd\SfToolsBundle\Twig\ImagesExtension
    tags: [ { name: twig.extension } ]
    arguments: [@service_container]

  rodgermd.twig.youtube_extension:
      class: Rodgermd\SfToolsBundle\Twig\YoutubeExtension
      tags: [ { name: twig.extension } ]

  rodgermd.vichuploader.namer_md5:
    class: Rodgermd\SfToolsBundle\Naming\MD5Namer
