services:
  rodgermd.type.image_file:
    class: Rodgermd\SfToolsBundle\Type\ImageFileType
    tags:
        - { name: form.type, alias: image_file }
  rodgermd.twig.images_extension:
    class: Rodgermd\SfToolsBundle\Twig\ImagesExtension
    tags: [ { name: twig.extension } ]
    arguments: [@service_container]

  rodgermd.vichuploader.namer_md5:
    class: Rodgermd\SfToolsBundle\Naming\MD5Namer
