services:
  rodgermd.type.image_file:
    class: Rodgermd\SfToolsBundle\Type\ImageType
    tags:
        - { name: form.type, alias: image }

  rodgermd.type.rich_text:
    class: Rodgermd\SfToolsBundle\Type\RichTextType
    tags:
      - { name: form.type, alias: rich_text }
  rodgermd.twig.images_extension:
    class: Rodgermd\SfToolsBundle\Twig\ImagesExtension
    tags: [ { name: twig.extension } ]
    arguments: [@service_container]

  rodgermd.vichuploader.namer_md5:
    class: Rodgermd\SfToolsBundle\Naming\MD5Namer
