services:
  rodgermd.twig.images_extension:
    class: Rodgermd\SfToolsBundle\Twig\ImagesExtension
    tags: [ { name: twig.extension } ]
    arguments: ['@rodgermd.manager.images']

  rodgermd.manager.images:
    class: Rodgermd\SfToolsBundle\Manager\ImagesManager
    arguments:
      - "@vich_uploader.templating.helper.uploader_helper"
      - "@vich_uploader.property_mapping_factory"
      - "@liip_imagine.templating.helper"
      - "@doctrine.orm.default_entity_manager"

  rodgermd.twig.youtube_extension:
    class: Rodgermd\SfToolsBundle\Twig\YoutubeExtension
    tags: [ { name: twig.extension } ]

  rodgermd.twig.countries_extension:
    class: Rodgermd\SfToolsBundle\Twig\CountriesExtension
    tags: [ { name: twig.extension } ]

  rodgermd.twig.string_extension:
    class: Rodgermd\SfToolsBundle\Twig\StringExtension
    tags: [ { name: twig.extension } ]

  rodgermd.vichuploader.namer_md5:
    class: Rodgermd\SfToolsBundle\Naming\MD5Namer

  rodgermd.vichuploader.directory_name:
    class: Rodgermd\SfToolsBundle\Naming\DirectoryLevelsNamer

